/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description Tên đăng nhập của người dùng (không được trùng)
             * @example tohoai123
             */
            username: string;
            /**
             * @description Họ và tên đầy đủ của người dùng.
             * @example Tô Hoài
             */
            fullName: string;
            /** @example tohoai@gmail.com */
            email: string;
            /**
             * @description Mật khẩu có ít nhất 6 ký tự.
             * @example tohoai321
             */
            password: string;
            /**
             * @description Vai trò của người dùng (ví dụ: ADMIN, AUTHOR, USER).
             * @example user
             * @enum {string}
             */
            role: "admin" | "author" | "user";
            /**
             * @description Bút danh (chỉ dành cho tác giả, có thể bỏ trống).
             * @example Pen Master
             */
            penName?: string;
            /**
             * @description Tiểu sử ngắn của người dùng (có thể bỏ trống).
             * @example Tôi là một tác giả chuyên viết tiểu thuyết.
             */
            bio?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
