export const ValidationRules = {
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 20,
  FULLNAME_MIN_LENGTH: 2,
  FULLNAME_MAX_LENGTH: 50,
  PASSWORD_MIN_LENGTH: 6,
  PENNAME_MAX_LENGTH: 50,
  BIO_MAX_LENGTH: 200,
};
